### ISSUE TITLE
Meteor code must always run within a Fiber

### ISSUE THREAD

**Issue by VioletaCalvo** [benjick/stripe-meteor#2]
Hi everyone!

When I try to create an account I get an error from meteor:

> Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.

I'm beginner in Meteor & Stripe so any help or suggestions will be welcome. My Meteor method is:

``` coffeescript
'createStripeAccount': (userData)->
    check userData,
      email: String
      userId: String
    Stripe = StripeAPI(TEST_SECRET_KEY)
    Stripe.accounts.create {
      managed: true
      country: 'FR'
      email: userData.email
    },(err, data) ->
      if err then console.error 'createStripeAccount error:', err
      else
        console.log 'createStripeAccount success '
        console.log 'fields needed for verification:', data.verification.fields_needed
        fields =
          userId: userData.userId
          stripeUserId: data.id
        StripeConnectedAccounts.insert fields
        Meteor.call 'updateStripeAccount', (userData.userId=userData.userId)
      return
    return
```

In know there is another package I could use (https://atmospherejs.com/benjick/stripe-native) but I think it doesn't supports Stripe Checkout and I need it.

Thank you in advance!

**Comment by benjick** [comment]
Hi

Stripe native doesn't support connect yet, but I'll do that next. I'll have
it up by the weekend end.

**Comment by benjick** [comment]
In the meantime take a look at http://stackoverflow.com/a/26226668

**Comment by VioletaCalvo** [comment]
OK, Thank you!!!

**Comment by benjick** [comment]
fwiw it does support accounts now
