### ISSUE TITLE
Publish Latest Build?

### ISSUE THREAD

**Issue by generalleger** [benjick/stripe-meteor#4]
I saw that you just updated the package to the latest Stripe API (thanks!). Are you planning on publishing this latest one so it is available via `meteor add`?  Currently, `meteor add benjick:stripe` grabs the prior version 3.6.0.

Cheers.

**Comment by benjick** [comment]
Hey

Just waiting on autopublish, sorry I didn't see the new version before
today. If it doesn't get auto I will do it manually tomorrow.

Feel free to open issues when I miss new releases

**Comment by generalleger** [comment]
@benjick cool, I've never published a package before.  didn't realize there was a delay on the publish.  Thanks!  I'll close this down.

**Comment by benjick** [comment]
No, it's isn't really, but I don't have any computer to publish at the
moment so I'm using https://autopublish.meteor.com/ at the moment :)

**Comment by generalleger** [comment]
@benjick Ahh, got it... looks like autopublish is throwing a weird error.  https://autopublish.meteor.com/log/XNZA8WNvzoAMyAwzN

**Comment by benjick** [comment]
Yep, I've reported it a few hours ago

**Comment by benjick** [comment]
We're up!

**Comment by generalleger** [comment]
Awesome, thanks!!
